export const travelCards = [
  {
    id: "africa-intro",
    type: "featured",
    title: "África",
    paragraphs: [
      "Criamos jornadas sob medida para quem busca paisagens grandiosas, hospedagens exclusivas e encontros marcantes com a vida selvagem africana.",
      "Entre savanas abertas, lodges elegantes e experiências guiadas por especialistas locais, cada etapa da viagem revela um continente intenso, autêntico e inesquecível.",
    ],
  },
  {
    id: "kenya",
    type: "compact",
    tag: "Safári",
    title: "Expedição fotográfica pelas planícies do Quênia",
    location: "Quênia",
    image: "/images/leao1.webp",
    imageAlt: "Leao em area de safari nas planicies do Quenia",
  },
  {
    id: "roteiros",
    type: "featured",
    title: "Roteiros pensados no seu ritmo",
    paragraphs: [
      "Do amanhecer na savana a jantares ao pôr do sol, cada roteiro combina conforto, deslocamentos bem planejados e momentos que fazem sentido para o seu estilo de viagem.",
      "Selecionamos experiências culturais, observação de fauna e cenários impressionantes para transformar a viagem em memória, e não apenas em itinerário.",
    ],
  },
  {
    id: "tanzania",
    type: "compact",
    tag: "Vida Selvagem",
    title: "Leões ao amanhecer em reservas privadas",
    location: "Tanzânia",
    image: "/images/leao2.webp",
    imageAlt: "Leoes ao amanhecer em reserva privada na Tanzania",
  },
  {
    id: "botsuana",
    type: "compact",
    tag: "Natureza",
    title: "Trilhas silenciosas para observar a fauna local",
    location: "Botsuana",
    image: "/images/hiena.webp",
    imageAlt: "Fauna local em trilha silenciosa na Botsuana",
  },
  {
    id: "golf",
    type: "compact",
    tag: "Exclusivo",
    title: "Dias de descanso entre golfe e paisagens abertas",
    location: "África do Sul",
    image: "/images/golf.webp",
    imageAlt: "Campo de golfe cercado por paisagens abertas na Africa do Sul",
  },
  {
    id: "romance",
    type: "compact",
    tag: "Romance",
    title: "Viagem a dois com hospedagens e experiências privadas",
    location: "Zanzibar",
    image: "/images/casal.webp",
    imageAlt: "Casal em viagem romantica com experiencia privada em Zanzibar",
  },
  {
    id: "namibia",
    type: "compact",
    tag: "Exploração",
    title: "Grandes encontros em cenários selvagens e raros",
    location: "Namíbia",
    image: "/images/leao3.webp",
    imageAlt: "Cenario selvagem na Namibia com encontro marcante com a fauna",
  },
  {
    id: "cta",
    type: "featured",
    topText:
      "Assim como no início da jornada, cada roteiro continua sendo pensado para aproximar você da essência da África com conforto, exclusividade e conexão real com cada destino.",
    ctaLabel: "Ver mais",
  },
];
